### PR TITLE
added some firms

### PR DESCRIPTION
**Pull request by silverly**

### CODE REVIEW

**Comment by hakluke** [comment]
Hey sorry @silverly I just merged another one so there are now conflicts, could you please merge these in and pop it in alphabetical order?

**Comment by silverly** [comment]
here you go @hakluke  <3

**Review by hakluke — APPROVED** [review]
Thanks! You're the best!

**Comment by codingo** [comment]
Are we sure Intalock is in Brisbane? I've never encountered them here.

**Pull request merged**
